// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7T4EGFNtdiCsYLq97S0V3Iso7JcMIgcg',
    appId: '1:465525405582:android:073b851ce04cc48f0616df',
    messagingSenderId: '465525405582',
    projectId: 'tasky-3f0ce',
    databaseURL: 'https://tasky-3f0ce-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tasky-3f0ce.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2CCMexs7UgTy80TLeRrTmfq0N8x8INMI',
    appId: '1:465525405582:ios:f78c31e667e92b360616df',
    messagingSenderId: '465525405582',
    projectId: 'tasky-3f0ce',
    databaseURL: 'https://tasky-3f0ce-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'tasky-3f0ce.appspot.com',
    iosClientId: '465525405582-cisv7kidilngcsb858tnvmr9jpf7g9ci.apps.googleusercontent.com',
    iosBundleId: 'com.example.taskyFlutter',
  );
}
